# map
    roads = [
    [[105, -2], [5, -2]],
    [[2, 105], [2, 5]],
    [[-105, 2], [-5, 2]],
    [[-2, -105], [-2, -5]],
    [[5, 2], [105, 2]],
    [[-2, 5], [-2, 105]],
    [[-5, -2], [-105, -2]],
    [[2, -5], [2, -105]],
    [[2, 5], [5, 2]],
    [[-5, 2], [5, 2]],
    [[-2, -5], [5, 2]],
    [[-5, 2], [-2, 5]],
    [[-2, -5], [-2, 5]],
    [[5, -2], [-2, 5]],
    [[-2, -5], [-5, -2]],
    [[5, -2], [-5, -2]],
    [[2, 5], [-5, -2]],
    [[5, -2], [2, -5]],
    [[2, 5], [2, -5]],
    [[-5, 2], [2, -5]]
    ]

legal_routes = [
    [0, 13, 5], [0, 15, 6], [0, 17, 7],
    [1, 8, 4], [1, 16, 6], [1, 18, 7],
    [2, 9, 4], [2, 11, 5], [2, 19, 7],
    [3, 10, 4], [3, 12, 5], [3, 14, 6]
    ]

traffic_lights = [0, 1, 2, 3]
traffic_lights_init_index = [0, 1, 0, 1]

# generation
arrival_times = [5, 5, 5, 5]

# generation
stochastic = true