# map
    roads = [
    # Inn til krysset
    [[-200, 5], [-5, 5]],    
    [[-5, -5], [-200, -5]], 

    [[5, 5], [200, 5]],
    [[200, -5], [5, -5]],

    [[5, -5], [5, -200]],    
    [[-5, -200], [-5, -5]], 

    [[-5, 5], [-5, 200]],
    [[5, 200], [5, 5]],

    # Inne i krysset
    [[5, 5], [-5, -5]],
    [[-5, 5], [-5, -5]],
    [[-5, -5], [5, -5]],
    [[5, -5], [5, 5]],
    [[5, -5], [-5, 5]],
    [[-5, 5], [5, 5]]
    ]
    

legal_routes = [[0], [3], [5], [7]]

traffic_lights = [0, 3, 5, 7]

# generation
arrival_times = [5, 5, 5, 5]

# generation
stochastic = true