# map
roads = [
    [[-200, 0], [200, 0]],     # 0
    [[200, 5], [-200, 5]]       # 1
    ]

legal_routes = [[0], [1]]

# generation
arrival_times = [1, 1]

traffic_lights = []


# generation
stochastic = true