# map
roads = [
    [[-600, 0], [0, 0]],    # 0
    [[0, 0], [600, 0]]      # 1
    ]

legal_routes = [[0, 1]]

traffic_lights = [0]
traffic_lights_is_init_green = [false]

# generation
arrival_times = [2]

# generation
stochastic = true